/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package restaurant;
import java.sql.PreparedStatement;
import javax.swing.*;  
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSetMetaData;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dell
 */
public class Categories extends javax.swing.JFrame {
 JFrame f;
     ;
    /**
     * Creates new form Categories
     */
 String url = "jdbc:sqlserver://DESKTOP-3IUD4G7\\FARIYAISLAM:49671;databaseName=RESTAURANTMANAGEMENT";
String user = "FARIYAISLAM";
String password = "123456";
    public Categories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCat = new javax.swing.JTextField();
        Jadd = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCatID = new javax.swing.JTextField();
        jdelete = new javax.swing.JButton();
        jView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();
        jback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        jcat.setBackground(new java.awt.Color(255, 51, 51));
        jcat.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jcat.setForeground(new java.awt.Color(255, 51, 51));
        jcat.setText("                                                                 FOOD CATEGORIES");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Category Name");

        jCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCatActionPerformed(evt);
            }
        });

        Jadd.setBackground(new java.awt.Color(0, 0, 0));
        Jadd.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        Jadd.setForeground(new java.awt.Color(255, 51, 51));
        Jadd.setText("ADD");
        Jadd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        Jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JaddActionPerformed(evt);
            }
        });

        jupdate.setBackground(new java.awt.Color(51, 51, 51));
        jupdate.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jupdate.setForeground(new java.awt.Color(255, 51, 51));
        jupdate.setText("UPDATE");
        jupdate.setActionCommand("jupdate\n");
        jupdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("             Category ID");

        jCatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCatIDActionPerformed(evt);
            }
        });

        jdelete.setBackground(new java.awt.Color(0, 0, 0));
        jdelete.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jdelete.setForeground(new java.awt.Color(255, 51, 51));
        jdelete.setText("DELETE");
        jdelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });

        jView.setBackground(new java.awt.Color(0, 0, 0));
        jView.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jView.setForeground(new java.awt.Color(255, 51, 51));
        jView.setText("VIEW");
        jView.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jadd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCatID, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCat)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jView, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCatID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jView)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jupdate)
                    .addComponent(Jadd))
                .addGap(29, 29, 29)
                .addComponent(jdelete)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        catTable.setBackground(new java.awt.Color(51, 51, 51));
        catTable.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        catTable.setForeground(new java.awt.Color(255, 51, 51));
        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "CategoryID", "Name"
            }
        ));
        jScrollPane1.setViewportView(catTable);

        jback.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jback.setForeground(new java.awt.Color(255, 51, 51));
        jback.setText("Back");
        jback.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jcat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jback, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jback)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCatActionPerformed

    private void JaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JaddActionPerformed
        // TODO add your handling code here:
         String url = "jdbc:sqlserver://DESKTOP-3IUD4G7\\FARIYAISLAM:49671;databaseName=RESTAURANTMANAGEMENT";
String user = "FARIYAISLAM";
String password = "123456";

String catName=jCat.getText();
try{
                Connection connection = DriverManager.getConnection(url,user,password);
             String sql = "INSERT INTO  CATEGORIES values ('"+catName+"')";
             Statement statement = connection.createStatement();
             
            
                  int rows =statement.executeUpdate(sql);
               
               
                  
                  if(rows>0){
               
                  
              
              
         
              DefaultTableModel db=(DefaultTableModel)catTable.getModel();
            
              Statement st=connection.createStatement();
             ResultSet rs=st.executeQuery("SELECT categoryId,categoryName FROM CATEGORIES");
              catTable.setModel(DbUtils.resultSetToTableModel(rs));
               jCat.setText("");
              jCatID.setText("");
               }
                  
                  
                  
}
catch(SQLException e){
JOptionPane.showMessageDialog(f,"Adding Unsuccessful.Try again","Message",JOptionPane.OK_OPTION);
}


    }//GEN-LAST:event_JaddActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        // TODO add your handling code here:
        String catName=jCat.getText();
        String s=jCatID.getText();
        int id=Integer.parseInt(s);
        System.out.println(catName);
        System.out.println(id);
try{
                Connection connection = DriverManager.getConnection(url,user,password);
                
             String sql ="UPDATE CATEGORIES SET categoryName=' "+catName+" ' WHERE categoryId="+id+" ";
             Statement statement = connection.createStatement();
             
           int rows =statement.executeUpdate("UPDATE CATEGORIES SET categoryName=' "+catName+" ' WHERE categoryId="+id+" ");
                 
                   //statement.close();
              
                  
                  if(rows>0){
               DefaultTableModel db=(DefaultTableModel)catTable.getModel();
              Object data1[]={catName};
              Statement st=connection.createStatement();
             ResultSet rs=st.executeQuery("SELECT categoryId,categoryName FROM CATEGORIES");
              catTable.setModel(DbUtils.resultSetToTableModel(rs));
               jCat.setText("");
              jCatID.setText("");
               }
                  }
catch(SQLException e){
JOptionPane.showMessageDialog(f,"Updating Unsuccessful.Try again","Message",JOptionPane.OK_OPTION);
}

        
        
        
    }//GEN-LAST:event_jupdateActionPerformed

    private void jCatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCatIDActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
       // String catName=jCat.getText();
        String s=jCatID.getText();
        int id=Integer.parseInt(s);
        System.out.println(id);
       // System.out.println(id);
try{
                Connection connection = DriverManager.getConnection(url,user,password);
                System.out.println("hello");
             String sql ="DELETE FROM CATEGORIES WHERE categoryId="+id+" ";
             Statement statement = connection.createStatement();
             
           int rows =statement.executeUpdate(sql);
                 
                   //statement.close();
               System.out.println(rows);
                  
                  if(rows>0){
               DefaultTableModel db=(DefaultTableModel)catTable.getModel();
           
              Statement st=connection.createStatement();
             ResultSet rs=st.executeQuery("SELECT categoryId,categoryName FROM CATEGORIES");
              catTable.setModel(DbUtils.resultSetToTableModel(rs));
              jCat.setText("");
              jCatID.setText("");
               }
                  }
catch(SQLException e){
JOptionPane.showMessageDialog(f,"Deleting Unsuccessful.Try again","Message",JOptionPane.OK_OPTION);
}
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewActionPerformed
       
        
        
        DefaultTableModel db=(DefaultTableModel)catTable.getModel();
             try{
                 Connection connection = DriverManager.getConnection(url,user,password);
              Statement st=connection.createStatement();
             ResultSet rs=st.executeQuery("SELECT categoryId,categoryName FROM CATEGORIES");
              catTable.setModel(DbUtils.resultSetToTableModel(rs));}
             catch(SQLException e){
JOptionPane.showMessageDialog(f," Unsuccessful.Try again","Message",JOptionPane.OK_OPTION);
}
    }//GEN-LAST:event_jViewActionPerformed

    private void jbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        Dashboard D=new Dashboard();
        D.setVisible(true);
    }//GEN-LAST:event_jbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jadd;
    private javax.swing.JTable catTable;
    public javax.swing.JTextField jCat;
    private javax.swing.JTextField jCatID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jView;
    private javax.swing.JButton jback;
    private javax.swing.JLabel jcat;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables
}
